language: bash
services: docker
before_install:
 - cd rest-with-springboot\ Docker/
 - echo "Estamos na pasta do docker"
script:
 - docker-compose build
before_deploy:
 - echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
deploy:
 provider: script
 script: 
   "docker push alanmeneguim/rest-api; docker push alanmeneguim/msqyl-rest-api;"
 on:
   branch: master
notifications:
 email: false
